### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by userzhao666** [syuchua/MY_QBOT#10]
为什么机器人无法使用联网功能。

**Comment by userzhao666** [comment]
模型使用的是Claude-3-5-sonnet，gpt的模型在网页调整了，但是配置了Claude无法调用GPT了。

**Comment by syuchua** [comment]
联网bug已修复，模型的话只能使用一个，model.json里配置了模型的话会覆盖config.json中gpt的配置

**Comment by userzhao666** [comment]
感谢作者。目前可以用了…我上面说的情况是这样的，我本来是调整好用gpt模型，已保存配置，然后无法使用，然后我打算去用claude，才可以用..
