### ISSUE TITLE
docker一键部署出现的问题

### ISSUE THREAD

**Issue by su16888** [syuchua/MY_QBOT#3]
四个容器中的my_qbot容器报错：
提示：
`Traceback (most recent call last):
File "/app/main.py", line 4, in <module>
from utils.boot import task, shutdown_handler
File "/app/utils/boot.py", line 7, in <module>
from app.Core.message import process_group_message, process_private_message
File "/app/app/Core/message.py", line 5, in <module>
from ..process.process_msg import process_chat_message
File "/app/app/process/process_msg.py", line 12, in <module>
from ..Core.command import handle_command
File "/app/app/Core/command.py", line 10, in <module>
from commands.plugin import (
File "/app/commands/plugin.py", line 2, in <module>
from git import Repo
ModuleNotFoundError: No module named 'git'`

**Comment by su16888** [comment]
缺少 GitPython 库

**Comment by syuchua** [comment]
> 缺少 GitPython 库

这里是用来实现通过命令下载插件的，不过好像有几个文件忘记push了，明天修，你可以先把commands/plugin.py里相关的部分注释掉，其他功能是正常的

**Comment by su16888** [comment]
> > 缺少 GitPython 库
> 
> 这里是用来实现通过命令下载插件的，不过好像有几个文件忘记push了，明天修，你可以先把commands/plugin.py里相关的部分注释掉，其他功能是正常的

好嘟佬，修好麻烦说一下，嘿嘿

**Comment by syuchua** [comment]
> > > 缺少 GitPython 库
> > 
> > 
> > 这里是用来实现通过命令下载插件的，不过好像有几个文件忘记push了，明天修，你可以先把commands/plugin.py里相关的部分注释掉，其他功能是正常的
> 
> 好嘟佬，修好麻烦说一下，嘿嘿
现在应该好了，今天开学，忙了一天

**Comment by su16888** [comment]
docker一键部署,docker logs napcat登录后出现：
linux-bugly: init bugly ...
InitBuglyManager
SetLogger
fatalSetup
GetDllPath: 33
pub_key_path: /opt/QQ/resources/app/pub.key
[BuglyManager.cpp][InitBuglyManager][212]InitBuglyManager path: /app/.config/QQ/crash_files/
BuglyManager/opt/QQ/resources/app/pub.key
[BuglyService.cpp][CreatDir][70]!!!begin to CreatDir 0: /app/.config/QQ/crash_files/
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
registBugly/opt/QQ/resources/app/pub.key
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.12-27597..
setParam/opt/QQ/resources/app/pub.key
StartWithOptions s/opt/QQ/resources/app/pub.key
StartWithOptions e/opt/QQ/resources/app/pub.key
PostDelayedTask s/opt/QQ/resources/app/pub.key
PostDelayedTask e/opt/QQ/resources/app/pub.key
linux-bugly: init bugly done.
2024-09-02 19:12:13 [[36mDEBUG[39m] () | 本账号数据/缓存目录： /app/.config/QQ/NapCat/data
2024-09-02 19:12:13 [[91mERROR[39m] () | [Core] [Config] 创建配置文件时发生错误: ENOENT: no such file or directory, open '/app/napcat/config/napcat.json'
2024-09-02 19:12:13 [[91mERROR[39m] () | [Core] [Config] 读取配置文件时发生错误: ENOENT: no such file or directory, open '/app/napcat/config/napcat_1632211865.json'
(node:35) UnhandledPromiseRejectionWarning: Error: Problem with log4js configuration: ({
appenders: {
FileAppender: {
type: 'file',
filename: '/app/napcat/logs/2024-09-02_19-11-43.048.log',
maxLogSize: 10485760,
layout: {
type: 'pattern',
pattern: '%d{yyyy-MM-dd hh:mm:ss} [%p] %X{userInfo} | %m'
}
},
ConsoleAppender: {
type: 'console',
layout: {
type: 'pattern',
pattern: '%d{yyyy-MM-dd hh:mm:ss} [%[%p%]] %X{userInfo} | %m'
}
}
},
categories: {
default: {
appenders: [ 'FileAppender', 'ConsoleAppender' ],
level: 'debug'
},
file: { appenders: [ 'FileAppender' ], level: undefined },
console: { appenders: [ 'ConsoleAppender' ], level: undefined }
}
}) - category "file" is not valid (must be an object with properties "appenders" and "level")
at /app/napcat/node_modules/log4js/lib/configuration.js:33:13
at Array.forEach (<anonymous>)
at Object.throwExceptionIf (/app/napcat/node_modules/log4js/lib/configuration.js:31:9)
at /app/napcat/node_modules/log4js/lib/categories.js:92:19
at Array.forEach (<anonymous>)
at /app/napcat/node_modules/log4js/lib/categories.js:90:17
at /app/napcat/node_modules/log4js/lib/configuration.js:51:35
at Array.forEach (<anonymous>)
at Object.configure (/app/napcat/node_modules/log4js/lib/configuration.js:51:13)
at Object.configure (/app/napcat/node_modules/log4js/lib/log4js.js:72:17)
(Use `qq --trace-warnings ...` to show where the warning was created)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/app/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!

**Comment by syuchua** [comment]
> docker一键部署,docker logs napcat登录后出现： linux-bugly: init bugly ... InitBuglyManager SetLogger fatalSetup GetDllPath: 33 pub_key_path: /opt/QQ/resources/app/pub.key [BuglyManager.cpp][InitBuglyManager][212]InitBuglyManager path: /app/.config/QQ/crash_files/ BuglyManager/opt/QQ/resources/app/pub.key [BuglyService.cpp][CreatDir][70]!!!begin to CreatDir 0: /app/.config/QQ/crash_files/ [BuglyService.cpp][registBugly][589]set signal stack [BuglyService.cpp][registSignalHandler][520]regist native handler registBugly/opt/QQ/resources/app/pub.key [BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.12-27597.. setParam/opt/QQ/resources/app/pub.key StartWithOptions s/opt/QQ/resources/app/pub.key StartWithOptions e/opt/QQ/resources/app/pub.key PostDelayedTask s/opt/QQ/resources/app/pub.key PostDelayedTask e/opt/QQ/resources/app/pub.key linux-bugly: init bugly done. 2024-09-02 19:12:13 [�[36mDEBUG�[39m] () | 本账号数据/缓存目录： /app/.config/QQ/NapCat/data 2024-09-02 19:12:13 [�[91mERROR�[39m] () | [Core] [Config] 创建配置文件时发生错误: ENOENT: no such file or directory, open '/app/napcat/config/napcat.json' 2024-09-02 19:12:13 [�[91mERROR�[39m] () | [Core] [Config] 读取配置文件时发生错误: ENOENT: no such file or directory, open '/app/napcat/config/napcat_1632211865.json' (node:35) UnhandledPromiseRejectionWarning: Error: Problem with log4js configuration: ({ appenders: { FileAppender: { type: 'file', filename: '/app/napcat/logs/2024-09-02_19-11-43.048.log', maxLogSize: 10485760, layout: { type: 'pattern', pattern: '%d{yyyy-MM-dd hh:mm:ss} [%p] %X{userInfo} | %m' } }, ConsoleAppender: { type: 'console', layout: { type: 'pattern', pattern: '%d{yyyy-MM-dd hh:mm:ss} [%[%p%]] %X{userInfo} | %m' } } }, categories: { default: { appenders: [ 'FileAppender', 'ConsoleAppender' ], level: 'debug' }, file: { appenders: [ 'FileAppender' ], level: undefined }, console: { appenders: [ 'ConsoleAppender' ], level: undefined } } }) - category "file" is not valid (must be an object with properties "appenders" and "level") at /app/napcat/node_modules/log4js/lib/configuration.js:33:13 at Array.forEach () at Object.throwExceptionIf (/app/napcat/node_modules/log4js/lib/configuration.js:31:9) at /app/napcat/node_modules/log4js/lib/categories.js:92:19 at Array.forEach () at /app/napcat/node_modules/log4js/lib/categories.js:90:17 at /app/napcat/node_modules/log4js/lib/configuration.js:51:35 at Array.forEach () at Object.configure (/app/napcat/node_modules/log4js/lib/configuration.js:51:13) at Object.configure (/app/napcat/node_modules/log4js/lib/log4js.js:72:17) (Use `qq --trace-warnings ...` to show where the warning was created) (node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) [BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly. [NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/app/.config/QQ/crash_files/rqd_record.eup. [NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!

更新一下docker-compose文件，把napcat映射的那个目录去掉试试，然后更新容器，`docker-compose down`，`docker-compose pull my_qbot`，`docker-compose up -d`

**Comment by su16888** [comment]
![QQ20240903-144800](https://github.com/user-attachments/assets/fa7086e5-c0b2-40d6-bda8-ccc34c4e3203)
还有一个图片上docker-compose.yaml的文件中，napcat部分和文档站的不一致，哪个是对的？

**Comment by syuchua** [comment]
> ![QQ20240903-144800](https://github.com/user-attachments/assets/fa7086e5-c0b2-40d6-bda8-ccc34c4e3203)
> 还有一个图片上docker-compose.yaml的文件中，napcat部分和文档站的不一致，哪个是对的？

用my_qbot，对应的是serves名，文档忘记改了

**Comment by su16888** [comment]
![QQ20240903-151702](https://github.com/user-attachments/assets/cadb4314-5e21-471c-ac8e-33578b265723)
报错内容：`[32m2024-09-03 07:15:49[0m | [31m[1mERROR[0m | - [31m[1m函数 chat_completion 在 3 次尝试后仍然失败: Cannot connect to host gcp.yuchu.me:443 ssl:default [Name or service not known][0m
[32m2024-09-03 07:15:49[0m | [31m[1mERROR[0m | - [31m[1m函数 chat_completion 执行出错: Cannot connect to host gcp.yuchu.me:443 ssl:default [Name or service not known][0m
[32m2024-09-03 07:15:49[0m | [31m[1mERROR[0m | - [31m[1mNetwork connection error during API request: Cannot connect to host gcp.yuchu.me:443 ssl:default [Name or service not known][0m
[32m2024-09-03 07:15:49[0m | [31m[1mERROR[0m | - [31m[1mError in process_chat_message: 网络连接错误，请检查网络状态后重试: Cannot connect to host gcp.yuchu.me:443 ssl:default [Name or service not known][0m
[32m2024-09-03 07:15:49[0m | [1mINFO[0m | - [1m`

**Comment by su16888** [comment]
![QQ20240903-153931](https://github.com/user-attachments/assets/f98853ee-8fbf-43bc-9d0d-ace0ed323b11)

```
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/app/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
```

**Comment by syuchua** [comment]
> 
> ![QQ20240903-153931](https://github.com/user-attachments/assets/f98853ee-8fbf-43bc-9d0d-ace0ed323b11)
> 
> ```
> [BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
> [NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/app/.config/QQ/crash_files/rqd_record.eup.
> [NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
> ```

没见过这种报错啊，重启下napcat容器试试呢？

**Comment by su16888** [comment]
没用，会不会是因为把napcat挂载去掉的原因？

**Comment by su16888** [comment]
重启了，无效，还是报错，难道是这个文件的容器路径或者挂载问题？

**Comment by syuchua** [comment]
> 重启了，无效，还是报错，难道是这个文件的容器路径或者挂载问题？

这个问题我今天也出现了，但是好像没什么影响，还能正常对话啊，你看看机器人目录下的logs文件夹里的那个app.log文件，里面有详细的日志
